Bu not defterinde şuana kadar yaptığımız herşeyi bir sınıf yapısı altında birleştirerek
bir katman oluşturacağız. Nöral ağlar birbirinden farklı katmanların bir araya gelmesi
ile oluşur. Örneğin evrişimsen sinir ağlarında, dense, maxpooling gibi farklı görevleri
olan katmnalar bulunur. Bu katmanları arka arkaya dizerek bir nöral ağ oluştururuz.

En temel nöral ağ yapısı aşağıdaki gibisir. Her nöral ağda girdiyi şekillendiren bir **Input
Layer** bir de sonucun gözlemleneceği **Output Layer** bulunur. Bu iki katman arasında bulunan
diğer katmanların hepsi **Hidden Layer** olarak adlandırlır. Hidden Layer'ların sayılar ve tipleri
kullanıcı tarafından belirlenir.

![](https://machinelearningmastery.com/wp-content/uploads/2021/08/neural_networks_21.png)

In [1]:
import cv2 as cv
import numpy as np

In [2]:
def prepare_the_image(imgPath):
    img = cv.imread(imgPath, cv.IMREAD_GRAYSCALE)
    img = img/255
    flatten = img.flatten()
    return flatten


In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [4]:
flattenV = prepare_the_image("../dataset/train/vertical.png")
flattenH = prepare_the_image("../dataset/train/horizontal.png")

In [5]:
dataset = np.array([flattenV, flattenH])
labels = np.array([[0, 1]]).T

Katman sınıfımızı oluşturmaya başlayalım. Biz en temel katman yapısını oluşturacağız bu
yüzden katmanımızın sadece iki işlevi olacak. Bunlar forward and back propagation işlemleri
olacaktır. Eğer sınıf oluşturmaya hakim iseniz geçtiğimiz not defterinde kullandığımız
fonksiyonları sınıfımızın içerisine entegre etmekten fazlasını yapmadığımı görebilirsiniz.

Farklı olarak sınıf çağırıldığında çalışacak bir consturcter merhodu tanımladım. Bu methodun
amacı katmana girecek matrisin boyutlarına bilmek istemem çünkü  işlemlerimi girdi boyutna
göre yapamam gerekli.

In [6]:
class Layer:
    def __init__(self, input_size, output_size):
        self.weights = np.random.rand(input_size, output_size)
        print("Starting weights are . . .")
        print(self.weights)

    def feed_forward(self, input):
        weighted_sum = np.dot(input, self.weights)
        output = sigmoid(weighted_sum)
        return output

    def back_propagation(self, input, output, labels):
        error = output - labels
        adjustment = error * sigmoid_der(output)
        weights_update = np.dot(input.T, adjustment)
        self.weights -= weights_update

Hemen aşağıda katmanımızı çağğıralım. 3x3 bir resimi düzleştridiğimiz de 9X1 bir matris elde
ederiz, bu şekilde katmanıma matris boyutumu belirtitiyorum. Sonrasında 10 tur boyunca katmanın
forward ve back propagation methodlarını çağırıyorum yani nöral ağımı eğitiyorum. En son
elde ettiğim sonuçları çıktı olarak gözlemleyebilirsiniz.

In [7]:
layer1 = Layer(9, 1)

Starting weights are . . .
[[0.53173132]
 [0.35509124]
 [0.35441351]
 [0.7142355 ]
 [0.15548032]
 [0.02430959]
 [0.16116283]
 [0.39326071]
 [0.66534123]]


In [8]:
for i in range(10):
    output = layer1.feed_forward(dataset)
    layer1.back_propagation(dataset, output, labels)

In [9]:
print("Input dataset :: \n", dataset)
print("Labels are :: \n", labels)
print("Final weights are . . . \n", layer1.weights)

Input dataset :: 
 [[0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]]
Labels are :: 
 [[0]
 [1]]
Final weights are . . . 
 [[ 0.53173132]
 [-0.59899535]
 [ 0.35441351]
 [ 1.2419897 ]
 [-0.27085207]
 [ 0.55206379]
 [ 0.16116283]
 [-0.56082589]
 [ 0.66534123]]
